time ../../appstream-glib/client/appstream-builder						\
	--api-version=0.8						\
	--add-cache-id							\
	--verbose							\
	--max-threads=1							\
	--old-metadata=./metadata/arch					\
	--log-dir=./logs						\
	--temp-dir=./tmp						\
	--cache-dir=../cache						\
	--packages-dir=/media/raid/Archive/Arch/packages		\
	--extra-appdata-dir=../../fedora-appstream/appdata-extra	\
	--output-dir=./metadata						\
	--screenshot-dir=./metadata/arch				\
	--basename=arch							\
	--screenshot-uri=http://www.archlinux.org/pub/screenshots/
